name: livingseed_media
description: "Living Seed Media."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  dio: ^5.8.0+1
  iconsax: ^0.0.8
  file_picker: ^9.2.3
  pdf: ^3.11.3
  path_provider: ^2.1.5
  syncfusion_flutter_calendar: ^29.1.33
  carousel_slider: ^5.1.1
  image_picker: ^1.1.2
  choice: ^2.3.2
  collection: ^1.19.0
  just_audio: ^0.10.5
  connectivity_plus: ^7.0.0
  syncfusion_flutter_pdfviewer: ^29.1.38
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  flutter_local_notifications: ^19.4.2
  flutter_any_logo: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/pdfs/
    - assets/audios/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
